"""Opt-in integration test. All temporary schemas are rolled back, never committed."""
import os
import tempfile
import unittest
import uuid
from datetime import date
from pathlib import Path
from unittest.mock import patch

from psycopg import sql

from etl.connectors.olap import get_olap_connection
from etl.dummy.generate import write_dataset
from etl.dummy.seed import SOURCE_TABLES, reset_source
from etl.pipeline.initial_load import RESET_TABLES, run_initial_load
from etl.pipeline.master import run_master_pipeline
from etl.control.locking import acquire_pipeline_lock


class ScopedCursor:
    def __init__(self, cursor, owner):
        self.cursor, self.owner = cursor, owner

    def __enter__(self):
        self.cursor.__enter__()
        return self

    def __exit__(self, *args):
        return self.cursor.__exit__(*args)

    def execute(self, query, params=None):
        return self.cursor.execute(self.owner.query(query), params)

    def copy(self, query):
        return self.cursor.copy(self.owner.query(query))

    def __getattr__(self, name):
        return getattr(self.cursor, name)


class ScopedConnection:
    """Route production SQL into isolated schemas on the test connection."""
    def __init__(self, conn, schema, control):
        self.conn, self.schema, self.control = conn, schema, control

    def query(self, query):
        text = query.as_string(self.conn) if isinstance(query, sql.Composable) else query
        return (text.replace('"public".', f'"{self.schema}".')
                    .replace('public.', f'"{self.schema}".')
                    .replace('etl_control.', f'"{self.control}".')
                    .replace('TO public', f'TO "{self.schema}"'))

    def cursor(self):
        self.conn.execute(sql.SQL('SET LOCAL search_path TO {}').format(sql.Identifier(self.schema)))
        return ScopedCursor(self.conn.cursor(), self)

    def execute(self, query, params=None):
        self.conn.execute(sql.SQL('SET LOCAL search_path TO {}').format(sql.Identifier(self.schema)))
        if params:
            params = tuple(p.replace('public.', self.schema + '.') if isinstance(p, str) and p.startswith('public.') else p for p in params)
        return self.conn.execute(self.query(query), params)


@unittest.skipUnless(os.getenv('RUN_POSTGRES_TESTS') == '1', 'Set RUN_POSTGRES_TESTS=1 for isolated PostgreSQL tests')
class PostgresInitialLoadTests(unittest.TestCase):
    def test_copy_constraints_and_rollback(self):
        self.check_profile('legacy', date(2026, 3, 1), date(2026, 3, 3))

    def test_jatim_copy_constraints_and_rollback(self):
        self.check_profile('jatim-202608', date(2026, 8, 3), date(2026, 8, 5))

    def check_profile(self, profile, start, end):
        token = uuid.uuid4().hex[:12]
        source_schema, target_schema, control = (f'dummy_test_{token}_{s}' for s in ('src', 'dst', 'ctl'))
        source_raw, target_raw = get_olap_connection(), get_olap_connection()
        try:
            source_raw.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(source_schema)))
            for schema in (target_schema, control):
                target_raw.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(schema)))
            for table in RESET_TABLES:
                target_raw.execute(sql.SQL('CREATE TABLE {} (LIKE {} INCLUDING ALL)').format(
                    sql.Identifier(target_schema, table), sql.Identifier('public', table)))
            for table in ('pipeline_runs', 'pipeline_state'):
                target_raw.execute(sql.SQL('CREATE TABLE {} (LIKE {} INCLUDING ALL)').format(
                    sql.Identifier(control, table), sql.Identifier('etl_control', table)))
            target_raw.execute(sql.SQL('ALTER TABLE {} ALTER COLUMN run_id DROP DEFAULT').format(sql.Identifier(control, 'pipeline_runs')))
            target_raw.execute(sql.SQL('ALTER TABLE {} ALTER COLUMN run_id ADD GENERATED BY DEFAULT AS IDENTITY').format(sql.Identifier(control, 'pipeline_runs')))
            source = ScopedConnection(source_raw, source_schema, control)
            target = ScopedConnection(target_raw, target_schema, control)
            source.execute(Path('etl/dummy/source.sql').read_text())
            source.execute('ALTER TABLE m_pegawai ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
            constraints = target_raw.execute("SELECT c.relname, con.conname, pg_get_constraintdef(con.oid) FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND con.contype='f'").fetchall()
            for table, name, definition in constraints:
                if table in RESET_TABLES:
                    target.execute(sql.SQL('ALTER TABLE {} ADD CONSTRAINT {} {}').format(
                        sql.Identifier(target_schema, table), sql.Identifier(name), sql.SQL(definition)))
            with tempfile.TemporaryDirectory() as directory:
                path = Path(directory) / 'source.gz'
                write_dataset(path, start, end, employees=205, profile=profile)
                reset_source(source, path, (*SOURCE_TABLES, 'm_previleges'))
                self.assertEqual(source.execute("SELECT nextval(pg_get_serial_sequence('m_pegawai', 'id'))").fetchone()[0], 206)
                self.assertEqual(source.execute('SELECT count(*) FROM m_pegawai WHERE status = 1').fetchone()[0], 205)
                self.assertEqual(source.execute('SELECT previleges FROM m_previleges WHERE id = 1').fetchone()[0], 'Pegawai Dummy')
                self.assertEqual(source.execute("SELECT nextval(pg_get_serial_sequence('m_previleges', 'id'))").fetchone()[0], 2)
                source.execute('SAVEPOINT before_failed_seed')
                with patch('etl.dummy.seed.copy_rows', side_effect=RuntimeError('injected source failure')):
                    with self.assertRaisesRegex(RuntimeError, 'injected source failure'):
                        reset_source(source, path, (*SOURCE_TABLES, 'm_previleges'))
                source.execute('ROLLBACK TO SAVEPOINT before_failed_seed')
                self.assertEqual(source.execute('SELECT count(*) FROM m_pegawai').fetchone()[0], 205)
                report = run_initial_load(source, target, start, end, apply=True)
                self.assertEqual(report['rows']['fact_kehadiran'], 615)
                if profile == 'jatim-202608':
                    self.assertEqual(report['rows']['dim_departemen'], 25)
                    self.assertEqual(report['rows']['dim_jadwal_kerja'], 125)
                self.assertEqual(target.execute('SELECT count(*) FROM analytical_user').fetchone()[0], 205)
                target.execute('SAVEPOINT before_failed_reload')
                with patch('etl.pipeline.initial_load.copy_rows', side_effect=RuntimeError('injected failure')):
                    with self.assertRaisesRegex(RuntimeError, 'injected failure'):
                        run_initial_load(source, target, start, end, apply=True)
                target.execute('ROLLBACK TO SAVEPOINT before_failed_reload')
                self.assertEqual(target.execute('SELECT count(*) FROM fact_kehadiran').fetchone()[0], 615)
                self.check_master(source, target, start, end)
        finally:
            # Never commit: this also removes all test schemas and their objects.
            source_raw.rollback()
            target_raw.rollback()
            source_raw.close()
            target_raw.close()

    def check_master(self, source, target, start, end):
        def snapshot():
            return {table: target.execute(
                f"SELECT coalesce(jsonb_agg(r ORDER BY r::text), '[]'::jsonb) FROM "
                f"(SELECT to_jsonb(t) - 'etl_loaded_at' AS r FROM {table} t) q"
            ).fetchone()[0] for table in (*RESET_TABLES, 'etl_control.pipeline_state')}

        before = snapshot()
        target.execute('SAVEPOINT before_failed_master')
        def fail_after_checkpoints(*args):
            self.assertEqual(target.execute('SELECT count(*) FROM etl_control.pipeline_state').fetchone()[0], 2)
            raise RuntimeError('injected after checkpoints')
        with patch('etl.pipeline.master.prepare_replacement', side_effect=fail_after_checkpoints):
            with self.assertRaisesRegex(RuntimeError, 'fact_kehadiran:.*injected after checkpoints'):
                run_master_pipeline(source, target, start_date=start, end_date=end, apply=True)
        target.execute('ROLLBACK TO SAVEPOINT before_failed_master')
        self.assertEqual(snapshot(), before)

        # Rebuild missing employee-days, including people without attendance events.
        target.execute('DELETE FROM fact_kehadiran WHERE tanggal = %s', (end,))
        run_master_pipeline(source, target, start_date=start, end_date=end, apply=True)
        self.assertEqual(target.execute('SELECT count(*) FROM fact_kehadiran').fetchone()[0], 615)
        first = snapshot()
        run_master_pipeline(source, target, start_date=start, end_date=end, apply=True)
        self.assertEqual(snapshot(), first)
        # The initial-load transaction holds the same key used by master/incremental.
        other = get_olap_connection()
        try:
            with self.assertRaisesRegex(RuntimeError, 'Another master'):
                acquire_pipeline_lock(other)
        finally:
            other.rollback()
            other.close()
