"""Exercise the real OLTP defaults and foreign keys in a rolled-back schema clone."""
import os
import tempfile
import unittest
import uuid
from datetime import date
from pathlib import Path
from unittest.mock import patch

from psycopg import sql

from etl.connectors.oltp import get_oltp_connection
from etl.dummy.generate import write_dataset
from etl.dummy.seed import reset_source
from test_initial_load_postgres import ScopedConnection


@unittest.skipUnless(os.getenv('RUN_POSTGRES_TESTS') == '1', 'Set RUN_POSTGRES_TESTS=1')
class SourceSchemaSeedTests(unittest.TestCase):
    def test_seed_against_actual_source_defaults_and_constraints(self):
        conn = get_oltp_connection()
        schema = 'seed_schema_test_' + uuid.uuid4().hex[:12]
        try:
            tables = [r[0] for r in conn.execute(
                "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename")]
            constraints = conn.execute("""
                SELECT c.relname, con.conname, pg_get_constraintdef(con.oid)
                FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid
                JOIN pg_namespace n ON n.oid=c.relnamespace
                WHERE n.nspname='public' AND con.contype='f'
            """).fetchall()
            serials = conn.execute("""
                SELECT table_name, column_name
                FROM information_schema.columns
                WHERE table_schema='public' AND column_default LIKE 'nextval(%%'
            """).fetchall()
            conn.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(schema)))
            for table in tables:
                conn.execute(sql.SQL('CREATE TABLE {} (LIKE {} INCLUDING ALL)').format(
                    sql.Identifier(schema, table), sql.Identifier('public', table)))
            # LIKE copies serial defaults referencing the original sequences.
            # Replace them with isolated identities BEFORE any fixture writes.
            for table, column in serials:
                conn.execute(sql.SQL('ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT').format(
                    sql.Identifier(schema, table), sql.Identifier(column)))
                conn.execute(sql.SQL('ALTER TABLE {} ALTER COLUMN {} ADD GENERATED BY DEFAULT AS IDENTITY').format(
                    sql.Identifier(schema, table), sql.Identifier(column)))
            source = ScopedConnection(conn, schema, schema)
            for table, name, definition in constraints:
                source.execute(sql.SQL('ALTER TABLE {} ADD CONSTRAINT {} {}').format(
                    sql.Identifier(schema, table), sql.Identifier(name), sql.SQL(definition)))
            with tempfile.TemporaryDirectory() as directory:
                path = Path(directory) / 'sample.gz'
                write_dataset(path, date(2026, 8, 1), date(2026, 8, 31),
                              employees=250, profile='jatim-202608')
                counts = reset_source(source, path, tables)
                self.assertEqual(counts['m_previleges'], 1)
                self.assertEqual(counts['m_pegawai'], 250)
                self.assertEqual(counts['t_perizinan'], 475)
                self.assertEqual(counts['t_checkinout'], 7600)
                self.assertEqual(source.execute('SELECT count(*) FROM m_pegawai WHERE status=1').fetchone()[0], 250)
                self.assertEqual(source.execute("SELECT nextval(pg_get_serial_sequence('m_previleges', 'id'))").fetchone()[0], 2)
                source.execute('SAVEPOINT before_failed_seed')
                with patch('etl.dummy.seed.copy_rows', side_effect=RuntimeError('injected failure')):
                    with self.assertRaisesRegex(RuntimeError, 'injected failure'):
                        reset_source(source, path, tables)
                source.execute('ROLLBACK TO SAVEPOINT before_failed_seed')
                self.assertEqual(source.execute('SELECT count(*) FROM m_previleges').fetchone()[0], 1)
                self.assertEqual(source.execute('SELECT count(*) FROM m_pegawai').fetchone()[0], 250)
        finally:
            conn.rollback()
            conn.close()
