-- ETL source contract only. Use a dedicated *_dummy database, not an application database.
CREATE TABLE IF NOT EXISTS m_departemen (id integer PRIMARY KEY, kode varchar(50) UNIQUE,
    nama_departemen varchar(255) NOT NULL, created_at timestamp);
CREATE TABLE IF NOT EXISTS m_previleges (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previleges varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS m_pegawai (id integer PRIMARY KEY, nip varchar(50) UNIQUE NOT NULL,
    nama varchar(255) NOT NULL, departemen integer NOT NULL REFERENCES m_departemen,
    status integer DEFAULT 1 REFERENCES m_previleges(id),
    created_at timestamp, updated_at timestamp);
CREATE TABLE IF NOT EXISTS m_user (id integer PRIMARY KEY, email varchar(255) NOT NULL,
    nama varchar(255) NOT NULL, pegawai_id integer REFERENCES m_pegawai,
    is_active boolean, last_login timestamp, created_at timestamp, updated_at timestamp);
CREATE TABLE IF NOT EXISTS m_shift (id integer PRIMARY KEY, nama varchar(255) NOT NULL,
    departemen_id integer REFERENCES m_departemen, is_flexible integer, created_at timestamp);
CREATE TABLE IF NOT EXISTS m_jadwal (id integer PRIMARY KEY, jenis integer NOT NULL REFERENCES m_shift,
    hari varchar(20) NOT NULL, jam_masuk time NOT NULL, jam_keluar time NOT NULL,
    jam_masuk_awal time NOT NULL, jam_keluar_akhir time NOT NULL, created_at timestamp);
CREATE TABLE IF NOT EXISTS m_tipe_ijin (id integer PRIMARY KEY, nama varchar(255) NOT NULL, tipe varchar(50));
CREATE TABLE IF NOT EXISTS m_jenis_ijin (id integer PRIMARY KEY, nama varchar(255) NOT NULL,
    kode varchar(50), tipe_id integer REFERENCES m_tipe_ijin, created_at timestamp);
CREATE TABLE IF NOT EXISTS m_hari_libur (id integer PRIMARY KEY, tanggal date NOT NULL,
    keterangan varchar(255), created_at timestamp);
CREATE TABLE IF NOT EXISTS t_libur_shift (id integer PRIMARY KEY, departemen_id integer REFERENCES m_departemen,
    pegawai_id integer REFERENCES m_pegawai, tanggal date, keterangan varchar(255),
    created_at timestamp, updated_at timestamp);
CREATE TABLE IF NOT EXISTS t_perizinan (id integer PRIMARY KEY, user_id integer NOT NULL REFERENCES m_user,
    nama varchar(255) NOT NULL, departemen integer NOT NULL REFERENCES m_departemen,
    pegawai_id integer REFERENCES m_pegawai, tipe_ijin integer NOT NULL REFERENCES m_tipe_ijin,
    jenis_ijin integer NOT NULL REFERENCES m_jenis_ijin, alasan text NOT NULL,
    approval boolean, approval_at timestamp, tgl_ijin date NOT NULL, tgl_ijin_sampai date,
    created_at timestamp, updated_at timestamp);
CREATE TABLE IF NOT EXISTS t_checkinout (id integer PRIMARY KEY, pegawai_id integer NOT NULL REFERENCES m_pegawai,
    departemen integer REFERENCES m_departemen, work_code integer NOT NULL, is_wfh smallint,
    created_at timestamp, updated_at timestamp);
CREATE INDEX IF NOT EXISTS dummy_attendance_date ON t_checkinout (created_at);
